apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
   name: ceph
provisioner: kubernetes.io/rbd
parameters:
    monitors: 127.0.0.1:6789
    adminId: admin
    adminSecretName: ceph-admin-key
    adminSecretNamespace: "ceph"
    pool: rbd
    userId: admin
    userSecretName: ceph-admin-key
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: gce
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  zone: europe-west1-a
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-osd
  labels:
    app: ceph
    daemon: osd
spec:
  ports:
  - port: 6800
    name: ceph
  clusterIP: None
  selector:
    app: ceph
    daemon: osd
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: ceph-osd
  namespace: ceph
  labels:
    app: ceph
    daemon: osd
spec:
  serviceName: "ceph-osd"
  replicas: 3
  volumeClaimTemplates:
    - metadata:
        name: osd-directory
        annotations:
          volume.alpha.kubernetes.io/storage-class: gce
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 500Gi
  template:
    metadata:
      labels:
        app: ceph
        daemon: osd
    spec:
      nodeSelector:
        storage: "true"
      volumes:
        - name: devices
          hostPath:
            path: /dev
        - name: ceph
          hostPath:
            path: /opt/ceph
        - name: ceph-conf
          secret:
            secretName: ceph-conf-combined
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: ceph-bootstrap-osd-keyring
        - name: ceph-bootstrap-mds-keyring
          secret:
            secretName: ceph-bootstrap-mds-keyring
        - name: ceph-bootstrap-rgw-keyring
          secret:
            secretName: ceph-bootstrap-rgw-keyring
      containers:
        - name: osd-pod
          image: ceph/daemon:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: devices
              mountPath: /dev
            - name: ceph
              mountPath: /var/lib/ceph
            - name: ceph-conf
              mountPath: /etc/ceph
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd
            - name: ceph-bootstrap-mds-keyring
              mountPath: /var/lib/ceph/bootstrap-mds
            - name: ceph-bootstrap-rgw-keyring
              mountPath: /var/lib/ceph/bootstrap-rgw
            - name: osd-directory
              mountPath: /var/lib/ceph/osd
          securityContext:
            privileged: true
          env:
            - name: CEPH_DAEMON
              value: osd_directory
            - name: KV_TYPE
              value: k8s
            - name: CLUSTER
              value: ceph
            - name: CEPH_GET_ADMIN_KEY
              value: "1"
          livenessProbe:
              tcpSocket:
                port: 6800
              initialDelaySeconds: 60
              timeoutSeconds: 5
          readinessProbe:
              tcpSocket:
                port: 6800
              timeoutSeconds: 5
